version: '3.8'
services:
  api:
    build:
      context: ./api
    ports:
      - "3333:3333"
    depends_on:
      - meals
      - users
      - roles
      - actions
      - menus
      - profile
      - authentication
      - schedules
      - users_roles

  users:
    build:
      context: ./api/microsservices/users
    ports:
      - "3001:3001"

  roles:
    build:
      context: ./api/microsservices/roles
    ports:
      - "3002:3002"

  actions:
    build:
      context: ./api/microsservices/actions
    ports:
      - "3003:3003"

  menus:
    build:
      context: ./api/microsservices/menus
    ports:
      - "3004:3004"

  profile:
    build:
      context: ./api/microsservices/profile
    ports:
      - "3005:3005"

  authentication:
    build:
      context: ./api/microsservices/authentication
    ports:
      - "3006:3006"

  meals:
    build:
      context: ./api/microsservices/meals
    ports:
      - "3007:3007"

  schedules:
    build:
      context: ./api/microsservices/schedules
    ports:
      - "3008:3008"

  users_roles:
    build:
      context: ./api/microsservices/users-roles
    ports:
      - "3009:3009"
